name: Notification Service CI Pipeline

on:
  push:
    branches:
      - refactor/notification-service

concurrency:
  group: notification-ci-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  sonar-scan:
    name: SonarQube Scan
    uses: ./.github/workflows/ci_sonar_scan.yaml
    secrets: inherit

  snyk-scan:
    name: Snyk Scan
    needs:
      - sonar-scan
    if: ${{ always() }}
    uses: ./.github/workflows/ci_snyk_scan.yaml
    secrets: inherit

  notify:
    name: Notification
    needs:
      - sonar-scan
      - snyk-scan
    if: ${{ needs.snyk-scan.outputs.snyk_status == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Snyk notification
        uses: ./.github/actions/send-notification
        with:
          pipeline_name: ${{ github.workflow }}
          repository_name: ${{ github.repository }}
          failure_reason: "Snyk Dependency Scan Failed"
          author: ${{ github.event.head_commit.author.name || github.actor }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          mail_from: ${{ secrets.MAIL_FROM }}
          mail_to: ${{ secrets.MAIL_TO }}
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}